name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DoozyX/clang-format-lint-action@v0.20
        with:
          source: "."
          exclude: "./ext"
          extensions: "hpp,cpp,hpp.in,cu"
          clangFormatVersion: 18
          style: file
